### ISSUE TITLE
How should I add the elements I want to add? I found that changing index.html will be overwritten.

### ISSUE THREAD

**Issue by 227575** [Meekdai/Gmeek#30]
Hello, I would like to ask why changing the html file in docs has no effect. I see that the file will be constantly updated back to the original template layout, so if I want to change and add some special effects such as Onimaruhanten, adding it directly to index.html will not take effect. I don’t know how to change the configuration file. What should I do? Revise?

**Comment by Meekdai** [comment]
It is invalid if you manually modify `index.html`. Because it will be overwritten every time GitHub executes actions. So if you need to add some custom functions, you can use custom `JS` and `CSS` functions. For details, see the link below. However, this article is written in Chinese, and you can use a translation tool.
https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

Also, if you can provide your repository address, I can see more clearly what you want to do.

**Comment by Meekdai** [comment]
I understand, this is not supported yet, this feature can be added in the future.

**Comment by Meekdai** [comment]
@227575 I currently implement the feature of hiding this button. You can do this by adding the `showPostSource` configuration to the config file.

```
"showPostSource":0,
```

Then use `Actions->build Gmeek->Run workflow->Run workflow` to rebuild.

**Comment by Meekdai** [comment]
@227575 I currently implement the feature of hiding this button. You can do this by adding the `showPostSource` configuration to the config file.

```
"showPostSource":0,
```

Then use `Actions->build Gmeek->Run workflow->Run workflow` to rebuild.
